### ISSUE TITLE
Add Firefox support

### ISSUE THREAD

**Issue by diafygi** [cmpolis/smart-table-scroll#1]
Tried the demo on Firefox 40.0 Ubuntu 14.04, and the effect doesn't work.

**Comment by marpstar** [comment]
Same in 42.0a2

**Comment by ogonkov** [comment]
Seems like some FF problem. The final `div`, that "make" whole table to have scroll have strange `top` value `2e+7px`. While Chrome got `20000000px`.

http://stackoverflow.com/questions/28260889/set-large-value-to-divs-height

**Comment by cmpolis** [comment]
Thanks for sharing the link! Have this working in FF with https://github.com/cmpolis/smart-table-scroll/commit/69b45e959bd5e57743fb4937fc9130cba0fa70b7 - also had to make the rows slightly shorter to have the demo work w/ 1 million rows in FF because of the max `height` value(see SO post).

**Comment by ogonkov** [comment]
@cmpolis it's would be nice to post warning about FF behaviour somewhere

**Comment by cmpolis** [comment]
Put a note in the Readme: https://github.com/cmpolis/smart-table-scroll#known-limitations
