### ISSUE TITLE
Copy items

### ISSUE THREAD

**Issue by joni2back** [cmpolis/smart-table-scroll#2]
Hello, this idea is so smart !

I have a doubts, what happens if I press CTRL+A, then CTRL+C in the document, just copy the current-DOM items really? (or something like search an item by browser-finder CTRL+F)

I guess the WhatsApp web platform is using something like this when is showing the group contact lists.

Thank you!!

**Comment by cmpolis** [comment]
Hi joni, thanks for the kind words! For things to respond to `ctrl+a + ctrl+c` or `ctrl+f`, they need to be in the DOM. However, if you are trying to export large amounts of text, there are cleaner solutions than having users select all, then copy and for search, you could implement a client side search and call `table.updateData` with the filtered dataset.
